/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://uatydkpibzbctdrnlb54zx6hve.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ipwbbuvyk5aqzc4zptz4j7gnky",
    "aws_cognito_identity_pool_id": "us-east-1:1389c428-77b4-44c4-aebe-773669be1f9a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_W52QAtfpb",
    "aws_user_pools_web_client_id": "3j6jn6t4vh1v76vqie2k4o69s2",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ukfs-storage-42da4ec5100054-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
